UPDATE beer.beer SET beer_picture = 'Test', description = 'The design reveals it: This beer comes from Bavaria! The specialty from the house of Egerer is balanced and tasty, with a good and surprisingly high amount of aromatic and bitter hops that give the beer a bittersweet character. The color is golden yellow, with a fine white foam crown. To quote the Brewmaster: "It''s like sunshine!"', name = 'Urtyp Hell Edel Bayer', abv = '4.9%', beer_country_fk = 3, beer_brewery_fk = 9, beer_style_fk = 3 WHERE beer_id = 1;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Blend of lambics aged 18 to 20 months and of Bergeron apricots.', name = 'Fou'' Foune', abv = '5.0%', beer_country_fk = 5, beer_brewery_fk = 1, beer_style_fk = 4 WHERE beer_id = 2;
UPDATE beer.beer SET beer_picture = 'Test', description = 'The heaviest of the Westvleteren beers, the 12 is a quadrupel style beer, which can be recognized by its yellow cap. Like the other Westvleteren beers, the bottle does not have a label, and the cap therefore has all the required information.', name = 'Trappist Westvleteren 12', abv = '10.2%', beer_country_fk = 5, beer_brewery_fk = 8, beer_style_fk = 5 WHERE beer_id = 3;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Hazelnut Liquor Barrel Aged Imperial Stout - 2018 Edition
Collaboration w. FrauGruber ', name = 'Black Rabbit', abv = '12.0%', beer_country_fk = 4, beer_brewery_fk = 7, beer_style_fk = 6 WHERE beer_id = 4;
UPDATE beer.beer SET beer_picture = 'Test', description = 'This barley wine is a blend of multiple batches of beer which were aged in different spirits oak barrels. It''s complex aroma and taste of oak, dark and sweet caramel, vanilla, coconut, cocoa, roast, dark fruits and berries is a product of a complex brewing combined with the long maturation time and in the end of time spent in oak barrels. It will cellar very well, but do not go in to decades of ageing. It is a sipper and perfect to share on a special occasion. ', name = 'Hagger Blend 1116', abv = '12.1%', beer_country_fk = 4, beer_brewery_fk = 5, beer_style_fk = 2 WHERE beer_id = 5;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Sweet Stout of Mine brings you back to the most blissful memories of your childhood with its taste of crème brûlée and vanilla and then kicks you back to reality with the punch it packs, reminding you that you’re all grown up now, enough that you can enjoy this kind of treat. With vegan lactose, so it can be enjoyed equally by everyone, this is our favourite kind of dessert nowadays. ', name = 'Sweet Stout of Mine', abv = '10.5%', beer_country_fk = 1, beer_brewery_fk = 3, beer_style_fk = 6 WHERE beer_id = 6;
UPDATE beer.beer SET beer_picture = 'Test', description = 'We named our beer after the psychedelic Tropicalia Samba music from the 70s. We always wanted to include a tropical ingredient in our beer and Hibiscus flowers fit the bill!', name = 'Tropikalia IPA', abv = '7.0%', beer_country_fk = 1, beer_brewery_fk = 4, beer_style_fk = 7 WHERE beer_id = 7;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Caramel stout aged for almost 6 months in oak barrels previously containing Arkanj brandy (Calvados) made by the Kovilj Monastery. ', name = '02 Kolaboracija Caramel Stout', abv = '10.0%', beer_country_fk = 2, beer_brewery_fk = 6, beer_style_fk = 6 WHERE beer_id = 8;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Milk Stout, smooth, full mouth feel. Strong body with distinctive flavours of coffee, cocoa, vanilla and tropical notes in the back, a real treat for the connoisseurs. Not for lactose intolerant.', name = 'Mikkeller Vista Milk Stout', abv = '5.8%', beer_country_fk = 2, beer_brewery_fk = 2, beer_style_fk = 8 WHERE beer_id = 9;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Flying Dogma Galaxy IPA is the first collaboration between two breweries between Serbia and USA! Crispy, fruity and a little bit spicy American style IPA, ideal for this spring days!', name = 'Flying Dogma Galaxy IPA', abv = '6.6%', beer_country_fk = 2, beer_brewery_fk = 2, beer_style_fk = 9 WHERE beer_id = 10;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Test description.', name = 'TestBeer', abv = '5.0%', beer_country_fk = null, beer_brewery_fk = 2, beer_style_fk = 3 WHERE beer_id = 11;
UPDATE beer.beer SET beer_picture = 'Test', description = 'Test description.', name = 'TestBeer', abv = '5.0%', beer_country_fk = null, beer_brewery_fk = 2, beer_style_fk = 3 WHERE beer_id = 12;
UPDATE beer.beertag SET beer_beer_id = 1, tag_tag_id = 3 WHERE beertag_id = 8;
UPDATE beer.beertag SET beer_beer_id = 5, tag_tag_id = 6 WHERE beertag_id = 9;
UPDATE beer.beertag SET beer_beer_id = 8, tag_tag_id = 2 WHERE beertag_id = 10;
UPDATE beer.beertag SET beer_beer_id = 5, tag_tag_id = 5 WHERE beertag_id = 11;
UPDATE beer.beertag SET beer_beer_id = 7, tag_tag_id = 2 WHERE beertag_id = 12;
UPDATE beer.beertag SET beer_beer_id = 3, tag_tag_id = 9 WHERE beertag_id = 13;
UPDATE beer.beertag SET beer_beer_id = 1, tag_tag_id = 1 WHERE beertag_id = 14;
UPDATE beer.beertag SET beer_beer_id = 8, tag_tag_id = 3 WHERE beertag_id = 15;
UPDATE beer.beertag SET beer_beer_id = 6, tag_tag_id = 2 WHERE beertag_id = 16;
UPDATE beer.beertag SET beer_beer_id = 5, tag_tag_id = 1 WHERE beertag_id = 17;
UPDATE beer.brewery SET name = 'Bierol' WHERE brewery_id = 7;
UPDATE beer.brewery SET name = 'Brasserie Cantillon' WHERE brewery_id = 1;
UPDATE beer.brewery SET name = 'Brauhaus Bevog' WHERE brewery_id = 5;
UPDATE beer.brewery SET name = 'Brouwerij De Sint-Sixtusabdij van Westvleteren' WHERE brewery_id = 8;
UPDATE beer.brewery SET name = 'Dogma Brewery' WHERE brewery_id = 2;
UPDATE beer.brewery SET name = 'Kabinet Brewery' WHERE brewery_id = 6;
UPDATE beer.brewery SET name = 'Metalhead' WHERE brewery_id = 3;
UPDATE beer.brewery SET name = 'Privatbrauerei H. Egerer' WHERE brewery_id = 9;
UPDATE beer.brewery SET name = 'White Stork Beer Co.' WHERE brewery_id = 4;
UPDATE beer.country SET name = 'Austria' WHERE country_id = 4;
UPDATE beer.country SET name = 'Belgium' WHERE country_id = 5;
UPDATE beer.country SET name = 'Bulgaria' WHERE country_id = 1;
UPDATE beer.country SET name = 'Germany' WHERE country_id = 3;
UPDATE beer.country SET name = 'Serbia' WHERE country_id = 2;
UPDATE beer.drank_beer SET user_user_id = 1, rating_rating_id = null, beer_beer_id = 1, column_5 = null WHERE beer_user_id = 1;
UPDATE beer.drank_beer SET user_user_id = 2, rating_rating_id = 3, beer_beer_id = 1, column_5 = null WHERE beer_user_id = 2;
UPDATE beer.drank_beer SET user_user_id = 1, rating_rating_id = null, beer_beer_id = 2, column_5 = null WHERE beer_user_id = 3;
UPDATE beer.drank_beer SET user_user_id = 1, rating_rating_id = null, beer_beer_id = 3, column_5 = null WHERE beer_user_id = 4;
UPDATE beer.drank_beer SET user_user_id = 1, rating_rating_id = null, beer_beer_id = 4, column_5 = null WHERE beer_user_id = 5;
UPDATE beer.drank_beer SET user_user_id = 2, rating_rating_id = null, beer_beer_id = 3, column_5 = null WHERE beer_user_id = 6;
UPDATE beer.drank_beer SET user_user_id = 3, rating_rating_id = null, beer_beer_id = 7, column_5 = null WHERE beer_user_id = 7;
UPDATE beer.drank_beer SET user_user_id = 4, rating_rating_id = null, beer_beer_id = 8, column_5 = null WHERE beer_user_id = 8;
UPDATE beer.drank_beer SET user_user_id = 5, rating_rating_id = null, beer_beer_id = 9, column_5 = null WHERE beer_user_id = 9;
UPDATE beer.drank_beer SET user_user_id = 2, rating_rating_id = null, beer_beer_id = 10, column_5 = null WHERE beer_user_id = 10;
UPDATE beer.drank_beer SET user_user_id = 1, rating_rating_id = null, beer_beer_id = 11, column_5 = null WHERE beer_user_id = 11;
UPDATE beer.drank_beer SET user_user_id = 2, rating_rating_id = null, beer_beer_id = 11, column_5 = null WHERE beer_user_id = 12;
UPDATE beer.drank_beer SET user_user_id = 1, rating_rating_id = null, beer_beer_id = 12, column_5 = null WHERE beer_user_id = 13;
UPDATE beer.rating SET rating_value = 1 WHERE rating_id = 1;
UPDATE beer.rating SET rating_value = 2 WHERE rating_id = 2;
UPDATE beer.rating SET rating_value = 3 WHERE rating_id = 3;
UPDATE beer.rating SET rating_value = 4 WHERE rating_id = 4;
UPDATE beer.rating SET rating_value = 5 WHERE rating_id = 5;
UPDATE beer.style SET name = 'Stout - Imperial / Double' WHERE style_id = 1;
UPDATE beer.style SET name = 'Barleywine ' WHERE style_id = 2;
UPDATE beer.style SET name = 'Lager - Helles' WHERE style_id = 3;
UPDATE beer.style SET name = 'Lambic - Fruit' WHERE style_id = 4;
UPDATE beer.style SET name = 'Belgian Quadrupel' WHERE style_id = 5;
UPDATE beer.style SET name = 'Stout - Imperial / Double Milk' WHERE style_id = 6;
UPDATE beer.style SET name = 'IPA - Red' WHERE style_id = 7;
UPDATE beer.style SET name = 'Stout - Milk / Sweet' WHERE style_id = 8;
UPDATE beer.style SET name = 'IPA - American' WHERE style_id = 9;
UPDATE beer.tag SET name = 'Coffee' WHERE tag_id = 1;
UPDATE beer.tag SET name = 'Caramel' WHERE tag_id = 2;
UPDATE beer.tag SET name = 'Light' WHERE tag_id = 3;
UPDATE beer.tag SET name = 'Dark' WHERE tag_id = 4;
UPDATE beer.tag SET name = 'Sweet' WHERE tag_id = 5;
UPDATE beer.tag SET name = 'Intense' WHERE tag_id = 6;
UPDATE beer.tag SET name = 'Fresh' WHERE tag_id = 7;
UPDATE beer.tag SET name = 'Wheat' WHERE tag_id = 8;
UPDATE beer.tag SET name = 'White' WHERE tag_id = 9;
UPDATE beer.tag SET name = 'Brown' WHERE tag_id = 10;
UPDATE beer.user SET first_name = 'Petar', last_name = 'Petrov', nickname = 'p3sho_93', email = 'pesho@gmail.com', picture = null WHERE user_id = 1;
UPDATE beer.user SET first_name = 'Jonh', last_name = '', nickname = 'Jony_123', email = 'Jony@gmail.com', picture = null WHERE user_id = 2;
UPDATE beer.user SET first_name = '', last_name = '', nickname = 'beer_master', email = 'master_beer@yahoo.com', picture = null WHERE user_id = 3;
UPDATE beer.user SET first_name = 'Maria', last_name = 'Spasova', nickname = 'Maria_db', email = 'marcheto@gmail.com', picture = null WHERE user_id = 4;
UPDATE beer.user SET first_name = '', last_name = 'Petrov', nickname = 'noFear', email = 'igracha@gmail.com', picture = null WHERE user_id = 5;
UPDATE beer.user SET first_name = 'Allah', last_name = 'Mehmedov', nickname = 'bai_mangal_jelezoto', email = 'ciganina_bate@gmail.com', picture = null WHERE user_id = 6;
UPDATE beer.user SET first_name = 'Allaha', last_name = 'aaaaaaaaa', nickname = 'aaaaaaa', email = 'aaaaaaaa', picture = null WHERE user_id = 7;
UPDATE beer.wish_beer SET user_user_id = 1, beer_beer_id = 2 WHERE beer_user_id = 1;
UPDATE beer.wish_beer SET user_user_id = 3, beer_beer_id = 4 WHERE beer_user_id = 2;
UPDATE beer.wish_beer SET user_user_id = 1, beer_beer_id = 1 WHERE beer_user_id = 3;
UPDATE beer.wish_beer SET user_user_id = 5, beer_beer_id = 2 WHERE beer_user_id = 4;
UPDATE beer.wish_beer SET user_user_id = 1, beer_beer_id = 11 WHERE beer_user_id = 5;
UPDATE beer.wish_beer SET user_user_id = 4, beer_beer_id = 8 WHERE beer_user_id = 6;
UPDATE beer.wish_beer SET user_user_id = 1, beer_beer_id = 8 WHERE beer_user_id = 7;
UPDATE beer.wish_beer SET user_user_id = 5, beer_beer_id = 3 WHERE beer_user_id = 8;
UPDATE beer.wish_beer SET user_user_id = 2, beer_beer_id = 2 WHERE beer_user_id = 9;
UPDATE beer.wish_beer SET user_user_id = 1, beer_beer_id = 10 WHERE beer_user_id = 10;
UPDATE beer.wish_beer SET user_user_id = 2, beer_beer_id = 10 WHERE beer_user_id = 11;
UPDATE beer.wish_beer SET user_user_id = 3, beer_beer_id = 10 WHERE beer_user_id = 12;